spring:
  application:
    name: Mover
  datasource:
    url: jdbc:mysql://localhost:3306/moverdb
    username: root
    password: "#KRBarman2004"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  server:
     port: 5631
     error:
       whitelabel:
          enabled: false
  thymeleaf:
    cache: false